<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ __('Weekly AI Project Report') }}</title>
</head>
<body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background-color:#f1f5f9;">
    <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f1f5f9;padding:32px 0;">
        <tr>
            <td align="center">
                <table width="640" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1);">
                    {{-- Header --}}
                    <tr>
                        <td style="background:linear-gradient(135deg,#7c3aed,#6d28d9);padding:32px 24px;text-align:center;">
                            <h1 style="margin:0;color:#fff;font-size:22px;font-weight:700;">{{ __('Weekly AI Project Report') }}</h1>
                            <p style="margin:8px 0 0;color:rgba(255,255,255,0.8);font-size:14px;">{{ now()->format('d/m/Y') }}</p>
                        </td>
                    </tr>
                    {{-- Body --}}
                    <tr>
                        <td style="padding:24px;">
                            <p style="margin:0 0 16px;color:#334155;font-size:15px;">
                                {{ __('Hi') }} <strong>{{ $userName }}</strong>,
                            </p>
                            <p style="margin:0 0 20px;color:#64748b;font-size:14px;">
                                {{ __('Here is your AI-generated weekly project summary:') }}
                            </p>
                            <div style="color:#334155;font-size:14px;line-height:1.7;">
                                {!! $reportHtml !!}
                            </div>
                        </td>
                    </tr>
                    {{-- Footer --}}
                    <tr>
                        <td style="padding:20px 24px;background-color:#f8fafc;border-top:1px solid #e2e8f0;text-align:center;">
                            <p style="margin:0;color:#94a3b8;font-size:12px;">
                                {{ __('Generated by AI Assistant') }} &bull; {{ config('app.name') }}
                            </p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>
</html>
