@component('emails.layout', [
    'subject' => __('Weekly AI Project Report'),
    'emailTitle' => __('Weekly AI Project Report'),
    'emailSubtitle' => now()->format('d/m/Y'),
])
    <p style="margin:0 0 16px; font-size:15px; color:#334155;">
        {{ __('Hi') }} <strong>{{ $userName }}</strong>,
    </p>
    <p style="margin:0 0 20px; font-size:14px; color:#64748b;">
        {{ __('Here is your AI-generated weekly project summary:') }}
    </p>
    <div style="color:#334155; font-size:14px; line-height:1.7; background:#f8fafc; border-radius:12px; padding:20px; border:1px solid #e2e8f0;">
        {!! $reportHtml !!}
    </div>
    <p style="margin:20px 0 0; font-size:12px; color:#94a3b8; text-align:center;">
        {{ __('Generated by AI Assistant') }}
    </p>
@endcomponent
